name: 构建应用程序

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        brew install upx

    - name: 使用 PyInstaller 构建
      run: |
        pyinstaller -D -i ./config/ota.ico \
          --exclude-module QtQml \
          --exclude-module QtQuick \
          --exclude-module QtVirtualKeyboard \
          --exclude-module QtPdf \
          --exclude-module QtOpenGL \
          --exclude-module QtNetwork \
          --exclude-module QtDBus \
          --upx-dir=$(brew --prefix upx)/bin \
          hid_tota_ota.py
        cp -R ./config ./dist/hid_tota_ota/
    
    - name: 压缩构建产物
      run: |
        cd dist
        zip -r hid_tota_ota.zip hid_tota_ota
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: hid_tota_ota
        path: dist/hid_tota_ota.zip
