name: 构建 macOS 应用程序

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: macos-latest
          - arch: arm64
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        brew install upx

    - name: 创建 .spec 文件
      run: |
        cat << EOF > hid_tota_ota.spec
        # -*- mode: python ; coding: utf-8 -*-

        block_cipher = None

        a = Analysis(['hid_tota_ota.py'],
                     pathex=[],
                     binaries=[],
                     datas=[('config', 'config')],
                     hiddenimports=[],
                     hookspath=[],
                     hooksconfig={},
                     runtime_hooks=[],
                     excludes=['QtQml', 'QtQuick', 'QtVirtualKeyboard', 'QtPdf', 'QtOpenGL', 'QtNetwork', 'QtDBus'],
                     win_no_prefer_redirects=False,
                     win_private_assemblies=False,
                     cipher=block_cipher,
                     noarchive=False)

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(pyz,
                  a.scripts,
                  [],
                  exclude_binaries=True,
                  name='hid_tota_ota',
                  debug=False,
                  bootloader_ignore_signals=False,
                  strip=False,
                  upx=True,
                  console=False,
                  disable_windowed_traceback=False,
                  codesign_identity=None,
                  entitlements_file=None , icon='config/ota.ico')

        coll = COLLECT(exe,
                       a.binaries,
                       a.zipfiles,
                       a.datas,
                       strip=False,
                       upx=True,
                       upx_exclude=[],
                       name='hid_tota_ota')
        EOF

    - name: 使用 PyInstaller 构建
      run: |
        pyinstaller --clean hid_tota_ota.spec
    
    - name: 压缩构建产物
      run: |
        cd dist
        zip -r hid_tota_ota_${{ matrix.arch }}.zip hid_tota_ota

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: hid_tota_ota_${{ matrix.arch }}
        path: dist/hid_tota_ota_${{ matrix.arch }}.zip

  create-universal2:
    needs: [build]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    
    - name: 创建 Universal2 二进制
      run: |
        mkdir universal2
        unzip hid_tota_ota_x86_64/hid_tota_ota_x86_64.zip -d universal2/x86_64
        unzip hid_tota_ota_arm64/hid_tota_ota_arm64.zip -d universal2/arm64
        lipo universal2/x86_64/hid_tota_ota/hid_tota_ota universal2/arm64/hid_tota_ota/hid_tota_ota -create -output universal2/hid_tota_ota
        cp -R universal2/arm64/hid_tota_ota/* universal2/
        rm -rf universal2/x86_64 universal2/arm64
        cd universal2
        zip -r ../hid_tota_ota_universal2.zip .
    
    - name: 上传 Universal2 构建产物
      uses: actions/upload-artifact@v3
      with:
        name: hid_tota_ota_universal2
        path: hid_tota_ota_universal2.zip
